name: 'my first container action'
description: 'Testing GitHub Container Action'
author: 'Sanjay Dubey'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Happy Coding'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
